# Generated by Django 5.2.7 on 2025-11-12 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='metric_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
