# Generated by Django 5.2.7 on 2025-11-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
