# Generated by Django 5.2.7 on 2025-11-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_library_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='library_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
