# Generated by Django 5.2.7 on 2025-11-10 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('Metric_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Metric_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.FloatField(default=1.0)),
                ('Value_Type', models.CharField(choices=[('float', 'Float'), ('int', 'Integer'), ('bool', 'Boolean'), ('text', 'Text')], default='float', max_length=10)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('Domain_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Domain_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Created_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('Library_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Library_Name', models.CharField(max_length=100)),
                ('Repository_URL', models.CharField(blank=True, max_length=255, null=True)),
                ('Programming_Language', models.CharField(blank=True, max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='api.domain')),
            ],
        ),
        migrations.CreateModel(
            name='LibraryMetricValue',
            fields=[
                ('Value_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Value', models.TextField()),
                ('Last_Modified', models.DateTimeField(auto_now=True)),
                ('Collected_By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('Library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.library')),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
            ],
        ),
    ]
