# Generated by Django 5.2.7 on 2025-10-27 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('Domain_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Domain_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Role_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('Library_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Library_Name', models.CharField(max_length=100)),
                ('Programming_Language', models.CharField(blank=True, max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libraries', to='api.domain')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.role')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='Created_By',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
    ]
