# Generated by Django 5.2.7 on 2025-10-30 00:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('Metric_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Metric_Name', models.CharField(max_length=100)),
                ('Description', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Weight', models.FloatField(default=1.0)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryMetricValue',
            fields=[
                ('Value_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Value', models.FloatField(default=0)),
                ('Evidence', models.TextField(blank=True, null=True)),
                ('Collected_By', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_Modified', models.DateTimeField(auto_now=True)),
                ('Library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.library')),
                ('Metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
            ],
        ),
    ]
