# Generated by Django 5.2.7 on 2025-11-12 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraries', '0001_initial'),
        ('metrics', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryMetricValue',
            fields=[
                ('value_ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(default=0)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('collected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraries.library')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metric')),
            ],
        ),
    ]
